export const FETCH_MATCHES_REQUEST = 'FETCH_MATCHES_REQUEST';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_FAILURE = 'FETCH_MATCHES_FAILURE';
export const SELECT_MATCH = 'SELECT_MATCH';
export const SELECT_TICKET_CATEGORY = 'SELECT_TICKET_CATEGORY';
export const ADD_TO_CART = 'ADD_TO_CART';
